version: '3.8'
networks:
  backend:
    driver: bridge
services:
  event-api:
    container_name: event-api
    image: event-image
    env_file:
      - .env
    environment:
      DB_HOST: '${DB_EVENT_HOST}'
      ASPNETCORE_ENVIRONMENT: Production
    ports:
      - "4220:4220"
      - "4221:4221"
    networks:
      - backend
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "curl --fail http://localhost:4221/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
